version: '3'
services:
  latency-test:
    image: mulatinho/latency-test:
    ports:
      - '8080:8080'
    restart: on-failure:3
    depends_on:
      - postgres
    environment:
      POSTGRES_ENABLE: 1
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASS: change-it-here
      POSTGRES_DB: change-it-here
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=100"
      ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change-it-here
      POSTGRES_DB: your_database
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-e utf8 --locale=c"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/var/lib/postgresql/data:z
