version: '3'
services:
  latency-test:
    image: mulatinho/latency-test:latest
    container_name: latency-test
    networks:
      - latency-test
    environment:
      REDIS_ENABLED: true
      REDIS_HOST: redis
      KAFKA_ENABLED: true
      KAFKA_HOST: kafka
      POSTGRES_ENABLED: true
      POSTGRES_HOST: postgres
      POSTGRES_USER: your-user
      POSTGRES_PASSWORD: change-this
      POSTGRES_DB: fake_db
    depends_on:
      - redis
      - kafka
      - postgresql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - latency-test
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - latency-test
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - latency-test
    ports:
      - "6379:6379"
  postgresql:
    image: postgres:latest
    container_name: postgres
    networks:
      - latency-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your-user
      POSTGRES_PASSWORD: change-this
      POSTGRES_DB: fake_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
