---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-test
  labels:
    app: latency-test
    namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: latency-test
    spec:
      containers:
      - name: latency-test
        image: mulatinho/latency-test:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do ./latency-test.sh; sleep 10; done"]
        env:
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        envFrom:
        - configMapRef:
            name: latency-configmap
