apiVersion: v1
kind: ConfigMap
metadata:
  name: latency-configmap
data:
  REDIS_ENABLED: true
  REDIS_HOST: redis
  KAFKA_ENABLED: true
  KAFKA_HOST: kafka
  POSTGRES_ENABLED: true
  POSTGRES_HOST: postgres
  POSTGRES_USER: your-user
  POSTGRES_PASSWORD: change-this
  POSTGRES_DB: fake_db
