---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-test
  labels:
    app: latency-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: latency-test
    spec:
      containers:
      - name: latency-test
        image: mulatinho/latency-test:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do ./latency-test.sh; sleep 10; done"]
        env:
        - name: POSTGRESENABLE
          value: "1"
        - name: REDISENABLE
          value: "1"
        - name: PGHOST
          value: "postgres"
        - name: PGUSER
          value: "postgres"
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: ZOOKEEPERHOST
          value: "zookeper-1"
        - name: KAFKAHOST
          value: "kafka-1"
        - name: REDISHOST
          value: "redis"
