name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [ "ubuntu-latest" ]

    env:
      REPO_NAME: ${{ github.event.repository.name }}

    container:
      image: mulatinho/build-c:alpine
      volumes:
        - /__w/${REPO_NAME}/${REPO_NAME}:/app

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List contents
        run: ls -lah /app

      - name: build
        run: make

      - name: test
        run: find tests/ -type f -executable | while read test; do ./$test; done

  publish:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Push to registry
        run: |-
          echo "$TOKEN" | docker login -u mulatinho --password-stdin
          docker build -t mulatinho/latency-test:1.0.$GITHUB_RUN_NUMBER .
          docker tag mulatinho/latency-test:1.0.$GITHUB_RUN_NUMBER mulatinho/latency-test:latest
          docker push mulatinho/latency-test:1.0.$GITHUB_RUN_NUMBER
          docker push mulatinho/latency-test:latest
        env:
          TOKEN: ${{ secrets.PAT_DOCKER }}
